### ISSUE TITLE
Implement Anchor Nav variation

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-nav#10]
## Is your feature request related to a problem? Please describe.

Design work has been completed per ticket #5 

## Describe the solution you'd like

Updated design work for mobile to be implemented into component.

**Comment by jordanjones243** [comment]
The plan discussed by @jason-capsule42 and I will be to create the Anchornav feature that represents the figma design, but without the animated content. We have discussed that there could be a solid amount of work behind that, so we want to create a version without animation first. Once completed, we will proceed to discuss with the team whether or not we would like to release the static version first or continue on with creating a version that has an animated side bar.
