### ISSUE TITLE
auro-skeleton: use of deprecated @alaskaairux/webcorestylesheets@3.7.3

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-nav#26]
### General Support Request

This component has a dependency on a deprecated version of the wcss.

Please update from @alaskaairux/webcorestylesheets@3.7.3 to latest (@aurodesignsystem/webcorestylesheets@5.0.4 or later)

### Possible Solution

@aurodesignsystem/webcorestylesheets@5.0.4 or later

**Comment by blackfalcon** [comment]
Duplicate issue 

- https://github.com/AlaskaAirlines/auro-nav/issues/27
