### ISSUE TITLE
404 Loading Auro Nav Documentation

### ISSUE THREAD

**Issue by ArcherScript** [AlaskaAirlines/auro-nav#34]
### Please verify the version of auro-nav you have installed

1.2.7

### Please describe the bug

Go to https://auro.alaskaair.com/components/auro/nav
Navigate to API
See 404

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

Documentation should load

### What browsers are you seeing the problem on?

Chrome

### Additional context

Able to reproduce on Firefox

### Exit criteria

Documentation can load without 404ing

**Comment by Patrick-Daly-AA** [comment]
This is currently a known issue, as we are working our way updating some naming of files on the back end.

**Comment by jordanjones243** [comment]
This issue has been addressed and fixed
