### ISSUE TITLE
Non-compliant ESM code references

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-nav#54]
Non-compliant ESM code references

### Please verify the version of auro-select you have installed

@latest

### Please describe the bug

See the following code

https://github.com/AlaskaAirlines/auro-nav/blob/2c11b4129c672784ba1098423be09701adcb52b9/src/auro-nav.js#L18-L21

Import endpoint does not have syntax prefix causing consumer's build to break. 

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Updated components should not break build pipelines. 

### What browsers are you seeing the problem on?

n/a

### Additional context

n/a

### Exit criteria

This issue can be closed once the incomplete code has been updated.

**Comment by Patrick-Daly-AA** [comment]
Closing as a duplicate (also it's already fixed.
