### ISSUE TITLE
Left navigation design

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-nav#6]
# Blueprint
[Documentation & research
](https://www.figma.com/file/e5SFMd5WwEB27iG2rcdPcU/Navigation?node-id=1%3A9088)
[Desktop design](https://www.figma.com/file/vgBapdyc1pqZGONvOOvmcJ/Left-Navigation?node-id=1908%3A8814&t=7L24WZtyFeK5ziZf-1)
[Mobile design](https://www.figma.com/file/vgBapdyc1pqZGONvOOvmcJ/Left-Navigation?node-id=1952%3A35184&t=7L24WZtyFeK5ziZf-1)

## Outline tasks

- [x] anatomy
- [x] color
- [x] typography
- [x] layout
- [x] spacing
- [x] animation/behavior
- [x] variants
- [x] states (hover, focus, active, focus-visible)
- [x] a11y

## Optional

- [x] Competitive analysis
- [x] research
- [x] site audit
- [x] usage audit
- [x] inspirational work

**Comment by jason-capsule42** [comment]
@leeejune Engineering approves design. Code work to be tracked in ticket #9.
